platform: stm32mp2: iac: add missing include
If CONFIG_TFM_HALT_ON_CORE_PANIC is enabled, there is a compilation
error in IAC driver:
stm32_iac.c:124:9: error: implicit declaration of function
 'tfm_hal_system_halt' [-Wimplicit-function-declaration]
  124 |         tfm_hal_system_halt();
      |         ^~~~~~~~~~~~~~~~~~~
Solve this by adding missing #include <tfm_hal_platform.h>.

Signed-off-by: Yann Gautier <yann.gautier@foss.st.com>
Change-Id: Iab30acce8a05d30862292709212442e94bf6e903
Reviewed-on: https://gerrit.st.com/c/mpu/oe/st/TF-M/trusted-firmware-m/+/513329
Domain-Review: Ludovic BARRE <ludovic.barre@foss.st.com>
ACI: CITOOLS <MDG-smet-aci-reviews@list.st.com>