platform: devicetree: pm: put code under CONFIG_PM_DEVICE flag
When compiling for A35 TDCID flavor, there is a compialtion error:
../stm32mp2xx/native_driver/include/pm/device.h:113:43:
 error: 'const struct device' has no member named 'pm'
  113 |                 struct pm_device *pm = dev->pm;
      |                                           ^~

This is because this field is under CONFIG_PM_DEVICE flag, and is then
removed before compilation step, and even if the compiler will remove
the code under if (IS_ENABLED(CONFIG_PM_DEVICE)) if the flag is not
enabled, it will be removed later. The code should then be, as for the
struct under: #ifdef CONFIG_PM_DEVICE.

Signed-off-by: Yann Gautier <yann.gautier@foss.st.com>
Change-Id: I05c85f229f6acefc75b1f0308f1f4953ec65bd51
Reviewed-on: https://gerrit.st.com/c/mpu/oe/st/TF-M/trusted-firmware-m/+/468914