platform: stm32mp2: fix link error with test s and ns off
The standard log api (printf) can not be used due to handler context.
But with TEST_S=OFF and TEST_NS=OFF, link error happen:
libplatform_s.a(stm32_iac.o): in function `IAC_IRQHandler'
undefined reference to `tfm_hal_output_spm_log'

So replace spm log api with direct stdio_output_string.

Change-Id: I6c8294b39357796793927646d505860dcc9a9bef
Signed-off-by: Ludovic Barre <ludovic.barre@foss.st.com>
Reviewed-on: https://gerrit.st.com/c/mpu/oe/st/TF-M/trusted-firmware-m/+/368579
ACI: CITOOLS <MDG-smet-aci-reviews@list.st.com>