psa-adac: prepare stm32mp21 target support
GIT_PROGRESS is enabled to avoid this issue:
[ 33%] Performing update step for 'libpsaadac-populate'
error: pathspec 'b9ecde472bd4;;' did not match any file(s) known to git

The line `add subdirectory(...)` is needed to comply with our TF-M version.

Change-Id: Ic4acc474dc8ea4d0eade846032ff5242151112d5
Signed-off-by: Amelie Delaunay <amelie.delaunay@foss.st.com>
Reviewed-on: https://gerrit.st.com/c/mpu/oe/st/TF-M/trusted-firmware-m/+/476170
Domain-Review: Ludovic BARRE <ludovic.barre@foss.st.com>
Reviewed-by: Ludovic BARRE <ludovic.barre@foss.st.com>
Reviewed-by: Yann GAUTIER <yann.gautier@foss.st.com>
ACI: CIBUILD <MDG-smet-aci-builds@list.st.com>
ACI: CITOOLS <MDG-smet-aci-reviews@list.st.com>